### ISSUE TITLE
Should `init_hardware` be marked `pub`?

### ISSUE THREAD

**Issue by defunctzombie** [lucazulian/mcp23017#11]
The readme example has `u.init_hardware()`. However, if I try to copy this example, rust complains with:

```
function `init_hardware` is private
```

Is this function meant to be `pub` or have I misunderstood how to use the example?

**Comment by lucazulian** [comment]
@defunctzombie yes, you are right, `init_hardware` function should be public. If you need, you can avoid using that function setting manually pins mode with `all_pin_mode` function
