### ISSUE TITLE
PinMode constants are mixed up

### ISSUE THREAD

**Issue by mrd0ll4r** [lucazulian/mcp23017#2]
The `PinMode` constants are mixed up, i.e. `INPUT` should be `1`, and `OUTPUT` should be `0`.

This, in combination with the `pm` function results in not being able to properly use `all_pin_mode`. (i.e. casting `1` to `u8` results in `0b00000001`, not `0b11111111`, which doesn't work with `write_register`.)

I forked your repository and fixed this, but I also changed a bunch of other things, so I'm not sure a PR of my fixing commit would be the best thing... your choice 😅 .

**Comment by lucazulian** [comment]
PR are always welcome!!!
