### ISSUE TITLE
write_bit checks for >HIGH

### ISSUE THREAD

**Issue by mrd0ll4r** [lucazulian/mcp23017#3]
The `write_bit` function checks for `>1`, which conflicts with the definition of `HIGH=1`.

(Same disclaimer as in the other issue)
I forked your repository and fixed this, but I also changed a bunch of other things, so I'm not sure a PR of my fixing commit would be the best thing... your choice 😅 .

**Comment by lucazulian** [comment]
PR are always welcome!!!
